fix(integration-common): Update integration-rest dependency version t…
blackducksoftware/detect-docker-inspector pull request #2
Opened 2023-01-26 23:39 UTC by niravrsynopsys

**JIRA Bug:**
[IDETECT-3588](https://jira-sig.internal.synopsys.com/browse/IDETECT-3588)

**Description:**
`integration-common` is a transitive dependency of `detect-docker-inspector` (used by the integration-rest library) and to ensure detect-docker-inspector uses the latest version of `integration-common`, we update the integration-rest version to the latest release version i.e. `10.3.6`

Detect run result on this project after updating the result: https://us1a-int-hub02.nprd.sig.synopsys.com/api/projects/48eeccab-a910-41d9-a3da-ef684f7e9a9f/versions/21419665-baca-4c9e-817e-bf7bf0effa33/vulnerability-bom?selectedItem=faa0e753-2bfe-4c75-abe2-64e87b2b7208

2023-01-27 18:40 UTC, stevebillings requested changes

2023-01-27 18:40 UTC, stevebillings commented on build.gradle
>      implementation 'com.synopsys.integration:hub-imageinspector-lib:14.1.3'
hub-imageinspector-lib should also be bumped up to the latest version.

2023-01-27 19:30 UTC, niravrsynopsys commented
Latest detect run BOM on this project:
https://us1a-int-hub02.nprd.sig.synopsys.com/api/projects/48eeccab-a910-41d9-a3da-ef684f7e9a9f/versions/21419665-baca-4c9e-817e-bf7bf0effa33/components

2023-01-30 14:04 UTC, stevebillings approved these changes

2023-01-30 14:53 UTC, merged